// GENERAL
export const CHANGE_LOCAL = 'CHANGE_LOCAL'
export const CHECK_LOGIN = 'CHECK_LOGIN'
export const RESET_AUTH = 'RESET_AUTH'
export const SET_PAGINATION = 'SET_PAGINATION'

// Settings
export const SET_SETTINGS = 'SET_SETTINGS'
export const TOGGLE_NOTIFY_BY = 'TOGGLE_NOTIFY_BY'
export const SET_PROGRESS = 'SET_PROGRESS'
export const CHECK_EXIT = 'CHECK_EXIT'

// POST
export const POST_LIST = 'POST_LIST'
export const POST_DELETE = 'POST_DELETE'
export const POST_COMMENT_LIST = 'POST_COMMENT_LIST'
export const POST_COMMENT_CREATE = 'POST_COMMENT_CREATE'
export const POST_LIKE = 'POST_LIKE'
